language: cpp
sudo: false

env:
  global:
    - "ARTIFACTS_AWS_REGION=us-east-1"
    - "ARTIFACTS_S3_BUCKET=vtest.musescore.org"
    - secure: "lVj+9BBtJIjW3CwfXstvNyYVn0AkXEwTyiPmp4BprcheP78WIqZNC0uG2RjG9MgyHbZkprE7zRdqR9YPWTitg+XYkkD6+jPHRO+PQFLARuiTAX9yhUO53yQQZC2wMkQ#+bFuZsFmz1rfAsPHx3bXeZAMsz+Qnh8D2yIqqV7qxwWw="
    - secure: "L+66yQZIZJTyIAfrG89ncKIkMAr4+UvaOZMsd420OSdnEH9kpdm5Kws8rG0VVLAtqhfQfi3K9DuC8Ub7IiXqil//h+I9WJ2LHKirWK0m/MkhTFC6hfi0uSnQCX/jud3Keewxf3ovgiKQvIw6VR37UC50YJM9+KhZKtsNYhGAdos="

matrix:
  fast_finish: true
  allow_failures:
            - env: "JOB=AppImage_x86_64"
            - env: "JOB=AppImage_i686"
            - env: "JOB=AppImage_armhf"
            - env: "JOB=MacOSX"
  include:
    # 1st parallel build job - debug build on Ubuntu
    - env: "JOB=Tests"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            # not white listed - alsa
            - libsndfile1
            - wget
            - make
            - ant
            - curl
            - libasound2-dev
            - portaudio19-dev
            - libsndfile1-dev
            - zlib1g-dev
            - libfreetype6-dev
            - libfontconfig1-dev
            - lame
            - libmp3lame-dev
            - libegl1-mesa-dev
            - libegl1-mesa
            - ccache
            - libpulse-dev
      cache:
        directories:
          - $HOME/.ccache
      before_install:
        - "source build/travis/job1_Tests/environment.sh"
      install:
        - "echo $NOTIFICATION_EMAIL"
      before_script:
        - "echo $NOTIFICATION_EMAIL"
      script:
        - "echo $NOTIFICATION_EMAIL"
      after_script:
        - ARTIFACTS_CACHE_CONTROL='public, max-age=315360000'
        - 'ARTIFACTS_PATHS="$(ls vtest/html | tr "\n" ":")" artifacts upload'

notifications:
  email:
    on_success: changed
    on_failure: always
  webhooks:
    # trigger Buildtime Trend Service to parse Travis CI log
    - https://buildtimetrend.herokuapp.com/travis
